import { test, expect } from '@playwright/test';
import crypto from 'crypto';
import { db } from '../../src/db';
import { users } from '../../src/db/schema';
import { eq } from 'drizzle-orm';

const baseUrl = 'http://localhost:3000';

test.describe('PIM Workflow Integrity', () => {

  test('Ops creates canonical product and Seller creates offer', async ({ page, request, context, browser }) => {
    
    // 1. Setup Ops User
    const opsEmail = `ops_${crypto.randomBytes(4).toString('hex')}@example.com`;
    const opsPassword = 'TestPassword123!';
    
    await test.step('Signup & Promote to Ops Admin', async () => {
      await page.goto(`${baseUrl}/signup`);
      await page.fill('input[name="fullName"]', 'Ops Admin');
      await page.fill('input[name="companyName"]', 'Rudrastra');
      await page.fill('input[type="email"]', opsEmail);
      await page.fill('input[type="password"]', opsPassword);
      await page.click('button[type="submit"]');
      await page.waitForLoadState('networkidle');

      // Promote in DB
      await db.update(users).set({ role: 'ADMIN' }).where(eq(users.email, opsEmail));

      // Login
      await page.goto(`${baseUrl}/login`);
      await page.fill('input[type="email"]', opsEmail);
      await page.fill('input[type="password"]', opsPassword);
      await page.click('button[type="submit"]');
      await page.waitForLoadState('networkidle');
    });
    
    await test.step('Ops creates Product Family', async () => {
      await page.goto('http://localhost:3000/ops/catalog/products/new');

      // Wait for the form engine to load
      await expect(page.locator('h1:has-text("Create Product Family")')).toBeVisible();

      // Step 1: Classification
      await page.locator('select').nth(0).selectOption({ index: 1 }); // select first manufacturer
      await page.locator('select').nth(1).selectOption({ index: 1 }); // select first category
      await page.getByRole('button', { name: 'Next: Basic Info' }).click();

      // Step 2: Basic Info
      const testTitle = `Test Product ${Date.now()}`;
      await page.getByPlaceholder('e.g. T-Motor MN4014').fill(testTitle);
      await page.getByPlaceholder('e.g. MN4014-400KV').fill('TEST-MPN-001');
      await page.locator('textarea').fill('This is a test description generated by Playwright.');
      await page.getByRole('button', { name: 'Next: Media' }).click();

      // Step 3: Media
      await page.setInputFiles('input[type="file"]', {
        name: 'test.jpg',
        mimeType: 'image/jpeg',
        buffer: Buffer.from('test image data generated by script') 
      });
      await page.waitForTimeout(1000); // simulate upload time
      await page.getByRole('button', { name: 'Next: Variants & Specs' }).click();

      // Step 4: Variants & Specs
      await page.getByPlaceholder('e.g. 400KV').fill('Variant A');
      await page.getByRole('button', { name: 'Create Product' }).click();

      // Verify successful creation redirects to products list
      await page.waitForURL(/.*\/ops\/catalog\/products/);
      // Wait for table to load
      await page.waitForSelector('table');
    });
    // Now, simulate a seller adding an offer.
    // In a full E2E, we'd log out and log in as seller. We can do that by clearing cookies.
    await test.step('Seller creates Offer', async () => {
      // Clear cookies to simulate a new session
      await context.clearCookies();

      const sellerEmail = `seller_${crypto.randomBytes(4).toString('hex')}@example.com`;
      const sellerPassword = 'TestPassword123!';
      
      await page.goto(`${baseUrl}/signup`);
      await page.fill('input[name="fullName"]', 'Seller User');
      await page.fill('input[name="companyName"]', 'Seller Corp');
      await page.fill('input[type="email"]', sellerEmail);
      await page.fill('input[type="password"]', sellerPassword);
      await page.click('button[type="submit"]');
      await page.waitForLoadState('networkidle');

      // Promote in DB to SELLER
      await db.update(users).set({ role: 'SELLER' }).where(eq(users.email, sellerEmail));

      // Login
      await page.goto(`${baseUrl}/login`);
      await page.fill('input[type="email"]', sellerEmail);
      await page.fill('input[type="password"]', sellerPassword);
      await page.click('button[type="submit"]');
      await page.waitForLoadState('networkidle');
      
      // Let's verify Customer PDP
      // We need to extract the product ID from the DOM or URL. Since we're lazy in this script, let's query the DB for the product.
      const [newProduct] = await db.query.products.findMany({
        orderBy: (products, { desc }) => [desc(products.createdAt)],
        limit: 1,
      });

      if (newProduct) {
        // Go to customer PDP
        await page.goto(`http://localhost:3000/products/${newProduct.id}`);
        
        // Verify PDP loaded with our info
        await expect(page.locator(`text=${newProduct.title}`)).toBeVisible();
        await expect(page.locator(`text=Variant A`)).toBeVisible();
        
        // Verify Media is present
        const imgCount = await page.locator('img').count();
        expect(imgCount).toBeGreaterThan(0);
      }
    });
  });
});
