import type { CapabilityDefinition } from './types';

export const CAPABILITIES: CapabilityDefinition[] = [
  // --- CATALOG ---
  {
    key: 'catalog.products',
    name: 'Products',
    description: 'Core product catalog access',
    type: 'PRODUCT',
    lifecycle: 'ACTIVE',
    dependencies: [],
  },
  {
    key: 'catalog.categories',
    name: 'Categories',
    description: 'Product categorization and taxonomy',
    type: 'PRODUCT',
    lifecycle: 'ACTIVE',
    dependencies: ['catalog.products'],
  },
  {
    key: 'catalog.manufacturers',
    name: 'Manufacturers',
    description: 'Manufacturer data and brand indexing',
    type: 'PRODUCT',
    lifecycle: 'ACTIVE',
    dependencies: ['catalog.products'],
  },
  {
    key: 'catalog.specifications',
    name: 'Product Specifications',
    description: 'Detailed technical specification matrix',
    type: 'PRODUCT',
    lifecycle: 'ACTIVE',
    dependencies: ['catalog.products'],
  },
  {
    key: 'catalog.mpn-resolution',
    name: 'MPN Resolution',
    description: 'Resolution of manufacturer part numbers to canonical products',
    type: 'PRODUCT',
    lifecycle: 'DEVELOPMENT',
    dependencies: ['catalog.specifications'],
  },
  {
    key: 'catalog.management',
    name: 'Catalog Management',
    description: 'Administrative tools for catalog moderation',
    type: 'PRODUCT',
    lifecycle: 'BETA',
    dependencies: ['catalog.products'],
  },

  // --- ENGINEERING ---
  {
    key: 'engineering.search',
    name: 'Engineering Search',
    description: 'Parameter-driven engineering search',
    type: 'ENGINEERING',
    lifecycle: 'ACTIVE',
    dependencies: ['catalog.products'],
  },
  {
    key: 'engineering.compare',
    name: 'Compare Products',
    description: 'Technical comparison engine',
    type: 'ENGINEERING',
    lifecycle: 'ACTIVE',
    dependencies: ['catalog.specifications'],
  },
  {
    key: 'engineering.compatibility',
    name: 'Compatibility Engine',
    description: 'Component compatibility validation',
    type: 'ENGINEERING',
    lifecycle: 'BETA',
    dependencies: ['catalog.specifications'],
  },
  {
    key: 'engineering.component-matching',
    name: 'Component Matching',
    description: 'Automated substitution and matching',
    type: 'ENGINEERING',
    lifecycle: 'BETA',
    dependencies: ['catalog.specifications'],
  },
  {
    key: 'engineering.propulsion-calculator',
    name: 'Propulsion Calculator',
    description: 'Drone propulsion system calculations',
    type: 'ENGINEERING',
    lifecycle: 'PLANNED',
    dependencies: ['catalog.specifications'],
  },
  {
    key: 'engineering.system-validation',
    name: 'System Validation',
    description: 'Full system architecture validation',
    type: 'ENGINEERING',
    lifecycle: 'PLANNED',
    dependencies: ['engineering.compatibility'],
  },
  {
    key: 'engineering.specification-analysis',
    name: 'Specification Analysis',
    description: 'Deep spec curve analysis',
    type: 'ENGINEERING',
    lifecycle: 'PLANNED',
    dependencies: ['catalog.specifications'],
  },
  {
    key: 'engineering.application-matching',
    name: 'Application Matching',
    description: 'Matching products to drone applications (e.g. FPV, Cinema)',
    type: 'ENGINEERING',
    lifecycle: 'PLANNED',
    dependencies: ['catalog.specifications'],
  },

  // --- COMMERCE ---
  {
    key: 'commerce.cart',
    name: 'Shopping Cart',
    description: 'Multi-seller cart engine',
    type: 'COMMERCE',
    lifecycle: 'ACTIVE',
    dependencies: ['catalog.products'],
  },
  {
    key: 'commerce.checkout',
    name: 'Checkout',
    description: 'Checkout workflow',
    type: 'COMMERCE',
    lifecycle: 'ACTIVE',
    dependencies: ['commerce.cart', 'finance.payments'],
  },
  {
    key: 'commerce.addresses',
    name: 'Addresses',
    description: 'Address management',
    type: 'COMMERCE',
    lifecycle: 'ACTIVE',
    dependencies: [],
  },
  {
    key: 'commerce.shipping-rates',
    name: 'Shipping Rates',
    description: 'Live carrier shipping rate calculation',
    type: 'COMMERCE',
    lifecycle: 'ACTIVE',
    dependencies: ['commerce.addresses'],
  },
  {
    key: 'commerce.orders',
    name: 'Orders',
    description: 'Customer order history and details',
    type: 'COMMERCE',
    lifecycle: 'ACTIVE',
    dependencies: ['commerce.checkout'],
  },
  {
    key: 'commerce.order-tracking',
    name: 'Order Tracking',
    description: 'Logistics tracking integration',
    type: 'COMMERCE',
    lifecycle: 'ACTIVE',
    dependencies: ['commerce.orders'],
  },
  {
    key: 'commerce.order-history',
    name: 'Order History',
    description: 'Historical order querying',
    type: 'COMMERCE',
    lifecycle: 'ACTIVE',
    dependencies: ['commerce.orders'],
  },
  {
    key: 'commerce.order-cancellation',
    name: 'Order Cancellation',
    description: 'Self-serve cancellation',
    type: 'COMMERCE',
    lifecycle: 'ACTIVE',
    dependencies: ['commerce.orders'],
  },
  {
    key: 'commerce.reorder',
    name: 'Reorder',
    description: 'One-click reorder functionality',
    type: 'COMMERCE',
    lifecycle: 'ACTIVE',
    dependencies: ['commerce.orders'],
  },
  {
    key: 'commerce.purchase-orders',
    name: 'Purchase Orders',
    description: 'B2B PO consumption and invoice generation',
    type: 'COMMERCE',
    lifecycle: 'ACTIVE',
    dependencies: ['commerce.orders', 'procurement.approvals'], // Consumer of procurement
  },
  {
    key: 'commerce.tax',
    name: 'Taxation',
    description: 'Tax and GST calculation',
    type: 'COMMERCE',
    lifecycle: 'ACTIVE',
    dependencies: [],
  },
  {
    key: 'commerce.documents',
    name: 'Documents',
    description: 'Invoices and receipt generation',
    type: 'COMMERCE',
    lifecycle: 'ACTIVE',
    dependencies: ['commerce.orders'],
  },
  {
    key: 'commerce.warranties',
    name: 'Warranties',
    description: 'Warranty tracking per order item',
    type: 'COMMERCE',
    lifecycle: 'ACTIVE',
    dependencies: ['commerce.orders'],
  },

  // --- FINANCE ---
  {
    key: 'finance.payments',
    name: 'Payments',
    description: 'Payment gateway integration',
    type: 'FINANCE',
    lifecycle: 'ACTIVE',
    dependencies: [],
  },
  {
    key: 'finance.payment-verification',
    name: 'Payment Verification',
    description: 'Webhooks and signature validation',
    type: 'FINANCE',
    lifecycle: 'ACTIVE',
    dependencies: ['finance.payments'],
  },
  {
    key: 'finance.refunds',
    name: 'Refunds',
    description: 'Refund processing',
    type: 'FINANCE',
    lifecycle: 'ACTIVE',
    dependencies: ['finance.payments'],
  },
  {
    key: 'finance.ledger',
    name: 'Ledger',
    description: 'Immutable double-entry financial ledger',
    type: 'FINANCE',
    lifecycle: 'ACTIVE',
    dependencies: ['finance.payments'],
  },
  {
    key: 'finance.invoices',
    name: 'Financial Invoices',
    description: 'B2B accounting invoices',
    type: 'FINANCE',
    lifecycle: 'ACTIVE',
    dependencies: ['finance.ledger'],
  },
  {
    key: 'finance.payouts',
    name: 'Payouts',
    description: 'Vendor payout routing',
    type: 'FINANCE',
    lifecycle: 'ACTIVE',
    dependencies: ['finance.ledger'],
  },
  {
    key: 'finance.seller-settlements',
    name: 'Seller Settlements',
    description: 'Batched settlements for sellers',
    type: 'FINANCE',
    lifecycle: 'ACTIVE',
    dependencies: ['finance.payouts'],
  },
  {
    key: 'finance.commission',
    name: 'Commission Engine',
    description: 'Marketplace take-rate calculations',
    type: 'FINANCE',
    lifecycle: 'ACTIVE',
    dependencies: ['finance.ledger'],
  },
  {
    key: 'finance.taxes',
    name: 'Financial Taxes',
    description: 'TCS/TDS and GST ledger entries',
    type: 'FINANCE',
    lifecycle: 'ACTIVE',
    dependencies: ['finance.ledger'],
  },
  {
    key: 'finance.reconciliation',
    name: 'Reconciliation',
    description: 'Bank and gateway reconciliation',
    type: 'FINANCE',
    lifecycle: 'PLANNED',
    dependencies: ['finance.ledger'],
  },
  {
    key: 'finance.credit-notes',
    name: 'Credit Notes',
    description: 'Accounting credit notes',
    type: 'FINANCE',
    lifecycle: 'BETA',
    dependencies: ['finance.ledger'],
  },
  {
    key: 'finance.financial-reports',
    name: 'Financial Reports',
    description: 'Ledger reporting',
    type: 'FINANCE',
    lifecycle: 'BETA',
    dependencies: ['finance.ledger'],
  },

  // --- PROCUREMENT ---
  {
    key: 'procurement.bom',
    name: 'Bill of Materials',
    description: 'BOM management',
    type: 'PROCUREMENT',
    lifecycle: 'ACTIVE',
    dependencies: ['catalog.products'],
  },
  {
    key: 'procurement.bom-validation',
    name: 'BOM Validation',
    description: 'Technical validation of BOM',
    type: 'PROCUREMENT',
    lifecycle: 'DEVELOPMENT',
    dependencies: ['procurement.bom', 'engineering.system-validation'],
  },
  {
    key: 'procurement.component-matching',
    name: 'Component Matching (Procurement)',
    description: 'Sourcing matching for BOM lines',
    type: 'PROCUREMENT',
    lifecycle: 'PLANNED',
    dependencies: ['procurement.bom'],
  },
  {
    key: 'procurement.compatibility-validation',
    name: 'BOM Compatibility',
    description: 'Compatibility checks across a BOM',
    type: 'PROCUREMENT',
    lifecycle: 'PLANNED',
    dependencies: ['procurement.bom', 'engineering.compatibility'],
  },
  {
    key: 'procurement.supplier-matching',
    name: 'Supplier Matching',
    description: 'Supplier discovery for BOM components',
    type: 'PROCUREMENT',
    lifecycle: 'PLANNED',
    dependencies: ['procurement.bom', 'seller.offers'],
  },
  {
    key: 'procurement.rfq',
    name: 'RFQ',
    description: 'Request for Quotation engine',
    type: 'PROCUREMENT',
    lifecycle: 'DEVELOPMENT',
    dependencies: ['procurement.bom'],
  },
  {
    key: 'procurement.rfq-comparison',
    name: 'RFQ Comparison',
    description: 'Quote comparison matrix',
    type: 'PROCUREMENT',
    lifecycle: 'PLANNED',
    dependencies: ['procurement.rfq'],
  },
  {
    key: 'procurement.projects',
    name: 'Projects',
    description: 'Procurement project organization',
    type: 'PROCUREMENT',
    lifecycle: 'DEVELOPMENT',
    dependencies: ['procurement.bom'],
  },
  {
    key: 'procurement.approvals',
    name: 'Approvals',
    description: 'Multi-stage approval workflows',
    type: 'PROCUREMENT',
    lifecycle: 'PLANNED',
    dependencies: ['procurement.projects'],
  },
  {
    key: 'procurement.purchase-orders',
    name: 'Procurement Purchase Orders',
    description: 'Authoritative ownership of procurement PO generation',
    type: 'PROCUREMENT',
    lifecycle: 'PLANNED',
    dependencies: ['procurement.approvals'], // Removed commerce dependency to prevent cycles
  },
  {
    key: 'procurement.procurement-history',
    name: 'Procurement History',
    description: 'Audit history of procurement lifecycle',
    type: 'PROCUREMENT',
    lifecycle: 'PLANNED',
    dependencies: ['procurement.purchase-orders'],
  },

  // --- SELLER ---
  {
    key: 'seller.profile',
    name: 'Seller Profile',
    description: 'Seller public and private profiles',
    type: 'SELLER',
    lifecycle: 'ACTIVE',
    dependencies: ['platform.organizations'],
  },
  {
    key: 'seller.verification',
    name: 'Verification',
    description: 'KYC and compliance verification',
    type: 'SELLER',
    lifecycle: 'ACTIVE',
    dependencies: ['seller.profile'],
  },
  {
    key: 'seller.onboarding',
    name: 'Onboarding',
    description: 'Seller onboarding workflows',
    type: 'SELLER',
    lifecycle: 'ACTIVE',
    dependencies: ['seller.verification'],
  },
  {
    key: 'seller.catalog-submissions',
    name: 'Catalog Submissions',
    description: 'Seller proposing new MPNs or products',
    type: 'SELLER',
    lifecycle: 'BETA',
    dependencies: ['seller.onboarding', 'catalog.products'],
  },
  {
    key: 'seller.offers',
    name: 'Seller Offers',
    description: 'Pricing and condition for a product',
    type: 'SELLER',
    lifecycle: 'ACTIVE',
    dependencies: ['seller.onboarding'],
  },
  {
    key: 'seller.pricing',
    name: 'Pricing Engine',
    description: 'Bulk pricing and tiering',
    type: 'SELLER',
    lifecycle: 'ACTIVE',
    dependencies: ['seller.offers'],
  },
  {
    key: 'seller.inventory',
    name: 'Inventory',
    description: 'Stock and warehouse management',
    type: 'SELLER',
    lifecycle: 'ACTIVE',
    dependencies: ['seller.offers'],
  },
  {
    key: 'seller.fulfillment',
    name: 'Fulfillment',
    description: 'Seller shipping operations',
    type: 'SELLER',
    lifecycle: 'ACTIVE',
    dependencies: ['seller.orders'],
  },
  {
    key: 'seller.orders',
    name: 'Seller Orders',
    description: 'Order management for sellers',
    type: 'SELLER',
    lifecycle: 'ACTIVE',
    dependencies: ['commerce.orders', 'seller.onboarding'],
  },
  {
    key: 'seller.returns',
    name: 'Seller Returns',
    description: 'Seller handling of returns',
    type: 'SELLER',
    lifecycle: 'ACTIVE',
    dependencies: ['seller.orders'],
  },
  {
    key: 'seller.warranty',
    name: 'Seller Warranty',
    description: 'Seller warranty claim management',
    type: 'SELLER',
    lifecycle: 'ACTIVE',
    dependencies: ['seller.orders'],
  },
  {
    key: 'seller.payouts',
    name: 'Seller Payouts',
    description: 'Tracking payouts from platform',
    type: 'SELLER',
    lifecycle: 'ACTIVE',
    dependencies: ['finance.ledger', 'seller.onboarding'],
  },
  {
    key: 'seller.documents',
    name: 'Seller Documents',
    description: 'Seller tax and compliance docs',
    type: 'SELLER',
    lifecycle: 'ACTIVE',
    dependencies: ['seller.onboarding'],
  },
  {
    key: 'seller.analytics',
    name: 'Seller Analytics',
    description: 'Sales and performance analytics',
    type: 'SELLER',
    lifecycle: 'ACTIVE',
    dependencies: ['seller.onboarding'],
  },
  {
    key: 'seller.notifications',
    name: 'Seller Notifications',
    description: 'Seller-specific alerts',
    type: 'SELLER',
    lifecycle: 'ACTIVE',
    dependencies: ['seller.onboarding'],
  },
  {
    key: 'seller.rfq',
    name: 'Seller RFQ',
    description: 'Responding to RFQs',
    type: 'SELLER',
    lifecycle: 'DEVELOPMENT',
    dependencies: ['procurement.rfq', 'seller.onboarding'],
  },

  // --- OPERATIONS ---
  {
    key: 'operations.dashboard',
    name: 'Ops Dashboard',
    description: 'Internal operations overview',
    type: 'OPERATIONS',
    lifecycle: 'ACTIVE',
    dependencies: [],
  },
  {
    key: 'operations.tickets',
    name: 'Tickets',
    description: 'Support ticketing system',
    type: 'OPERATIONS',
    lifecycle: 'ACTIVE',
    dependencies: [],
  },
  {
    key: 'operations.ticket-routing',
    name: 'Ticket Routing',
    description: 'Automated ticket assignments',
    type: 'OPERATIONS',
    lifecycle: 'PLANNED',
    dependencies: ['operations.tickets'],
  },
  {
    key: 'operations.ticket-escalation',
    name: 'Ticket Escalation',
    description: 'Escalation workflows',
    type: 'OPERATIONS',
    lifecycle: 'PLANNED',
    dependencies: ['operations.tickets'],
  },
  {
    key: 'operations.ticket-sla',
    name: 'Ticket SLA',
    description: 'SLA monitoring and alerts',
    type: 'OPERATIONS',
    lifecycle: 'PLANNED',
    dependencies: ['operations.tickets'],
  },
  {
    key: 'operations.rma',
    name: 'RMA Management',
    description: 'Return Merchandise Authorization',
    type: 'OPERATIONS',
    lifecycle: 'ACTIVE',
    dependencies: ['commerce.orders'],
  },
  {
    key: 'operations.returns',
    name: 'Returns Logistics',
    description: 'Physical return processing',
    type: 'OPERATIONS',
    lifecycle: 'ACTIVE',
    dependencies: ['operations.rma'],
  },
  {
    key: 'operations.replacements',
    name: 'Replacements',
    description: 'Dispatching replacement units',
    type: 'OPERATIONS',
    lifecycle: 'BETA',
    dependencies: ['operations.rma'],
  },
  {
    key: 'operations.warranty',
    name: 'Warranty Claims',
    description: 'Managing customer warranty claims',
    type: 'OPERATIONS',
    lifecycle: 'ACTIVE',
    dependencies: ['commerce.orders'],
  },
  {
    key: 'operations.disputes',
    name: 'Disputes',
    description: 'Managing seller-buyer disputes',
    type: 'OPERATIONS',
    lifecycle: 'BETA',
    dependencies: ['commerce.orders'],
  },
  {
    key: 'operations.shipping',
    name: 'Operations Shipping',
    description: 'Platform shipping interventions',
    type: 'OPERATIONS',
    lifecycle: 'ACTIVE',
    dependencies: ['commerce.orders'],
  },
  {
    key: 'operations.delivery',
    name: 'Delivery Management',
    description: 'Last-mile logistics tracking',
    type: 'OPERATIONS',
    lifecycle: 'ACTIVE',
    dependencies: ['operations.shipping'],
  },
  {
    key: 'operations.fulfillment',
    name: 'Platform Fulfillment',
    description: 'Rudraastra-managed fulfillment',
    type: 'OPERATIONS',
    lifecycle: 'PLANNED',
    dependencies: ['operations.shipping'],
  },
  {
    key: 'operations.reconciliation',
    name: 'Operations Reconciliation',
    description: 'Operational sanity checks against ledger',
    type: 'OPERATIONS',
    lifecycle: 'BETA',
    dependencies: ['finance.ledger'],
  },
  {
    key: 'operations.customer-support',
    name: 'Customer Support',
    description: 'Buyer support tooling',
    type: 'OPERATIONS',
    lifecycle: 'ACTIVE',
    dependencies: ['operations.tickets'],
  },
  {
    key: 'operations.seller-support',
    name: 'Seller Support',
    description: 'Seller support tooling',
    type: 'OPERATIONS',
    lifecycle: 'ACTIVE',
    dependencies: ['operations.tickets'],
  },
  {
    key: 'operations.notifications',
    name: 'System Notifications',
    description: 'Global notification broadcasting',
    type: 'OPERATIONS',
    lifecycle: 'ACTIVE',
    dependencies: [],
  },
  {
    key: 'operations.audit',
    name: 'Ops Audit',
    description: 'Platform-wide security auditing',
    type: 'OPERATIONS',
    lifecycle: 'ACTIVE',
    dependencies: ['platform.audit-logs'],
  },
  {
    key: 'operations.incident-management',
    name: 'Incident Management',
    description: 'Handling platform-wide incidents',
    type: 'OPERATIONS',
    lifecycle: 'PLANNED',
    dependencies: ['operations.tickets'],
  },

  // --- PLATFORM ---
  {
    key: 'platform.account',
    name: 'User Accounts',
    description: 'Core user identity',
    type: 'PLATFORM',
    lifecycle: 'ACTIVE',
    dependencies: [],
  },
  {
    key: 'platform.organizations',
    name: 'Organizations',
    description: 'B2B Org management',
    type: 'PLATFORM',
    lifecycle: 'ACTIVE',
    dependencies: ['platform.account'],
  },
  {
    key: 'platform.rbac',
    name: 'RBAC',
    description: 'Role Based Access Control',
    type: 'PLATFORM',
    lifecycle: 'ACTIVE',
    dependencies: ['platform.organizations'],
  },
  {
    key: 'platform.audit-logs',
    name: 'Audit Logs',
    description: 'Immutable system audit logging',
    type: 'PLATFORM',
    lifecycle: 'ACTIVE',
    dependencies: [],
  },
  {
    key: 'platform.notifications',
    name: 'Platform Notifications',
    description: 'Low-level notification delivery',
    type: 'PLATFORM',
    lifecycle: 'ACTIVE',
    dependencies: [],
  },
];
